import prisma from "@/lib/prisma";
import { notFound, redirect } from "next/navigation";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";
import { ArrowLeft, Mic, Clock, Calendar, FileText, PlayCircle } from "lucide-react";
import { UserProfile } from "@/components/user-profile";

export default async function AudioDetailPage({ params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);

  if (!session || !session.user) {
    redirect("/login");
  }

  const audio = await prisma.audio.findUnique({
    where: { id: params.id },
  });

  if (!audio || audio.userId !== session.user.id) {
    notFound();
  }

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header - Soft shadow, no border */}
      <header className="sticky top-0 z-50 w-full bg-white/80 backdrop-blur-xl shadow-sm">
        <div className="container mx-auto px-4 lg:px-8 h-20 flex items-center justify-between">
          <div className="flex items-center gap-6">
            <Link 
              href="/" 
              className="flex items-center justify-center w-10 h-10 bg-slate-50 text-slate-500 hover:bg-blue-50 hover:text-blue-600 rounded-full transition-colors"
              title="Back to Workspace"
            >
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <div className="w-px h-8 bg-slate-200" />
            <div className="flex items-center gap-3 font-semibold text-xl text-slate-800 tracking-tight">
              <div className="bg-blue-600 p-2 rounded-xl shadow-blue-600/20 shadow-md">
                <Mic className="w-4 h-4 text-white" />
              </div>
              AudioTranscribe
            </div>
          </div>
          <UserProfile />
        </div>
      </header>

      <main className="flex-1 container max-w-5xl mx-auto px-4 lg:px-8 py-10 lg:py-16">
        <div className="mb-10">
          <div className="flex flex-col md:flex-row md:items-start justify-between gap-6">
            <div>
              <div className="flex items-center gap-4 mb-3">
                <h1 className="text-4xl font-bold tracking-tight text-slate-900">{audio.title}</h1>
                {audio.transcript ? (
                  <Badge className="bg-emerald-50 text-emerald-700 hover:bg-emerald-100 border-0 shadow-none text-sm px-3 py-1">Completed</Badge>
                ) : (
                  <Badge className="bg-amber-50 text-amber-700 hover:bg-amber-100 border-0 shadow-none text-sm px-3 py-1">Processing</Badge>
                )}
              </div>
              <div className="flex items-center gap-6 text-base font-medium text-slate-500">
                <span className="flex items-center gap-2">
                  <Calendar className="w-5 h-5 text-slate-400" />
                  {new Date(audio.createdAt).toLocaleDateString(undefined, {
                    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
                  })}
                </span>
                <span className="flex items-center gap-2">
                  <Clock className="w-5 h-5 text-slate-400" />
                  {new Date(audio.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </span>
              </div>
            </div>
          </div>
        </div>

        <div className="w-full space-y-6">
          <div className="bg-white rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] overflow-hidden flex flex-col min-h-[600px]">
            <div className="p-8 border-b border-slate-100 bg-white/50">
              <h2 className="text-xl font-bold flex items-center gap-2 text-slate-800">
                <div className="p-2 bg-indigo-50 text-indigo-600 rounded-lg">
                  <FileText className="w-5 h-5" />
                </div>
                Transcript
              </h2>
              <p className="text-sm text-slate-500 mt-2">Generated by Google Vertex AI</p>
            </div>
            
            <div className="flex-1 bg-slate-50/50">
              <ScrollArea className="h-[600px] w-full">
                <div className="p-8 md:p-12 max-w-4xl mx-auto">
                  {audio.transcript ? (
                    <div className="prose prose-slate prose-lg max-w-none">
                      <div className="whitespace-pre-wrap leading-[2.2] text-[1.1rem] text-slate-700">
                        {audio.transcript}
                      </div>
                    </div>
                  ) : (
                    <div className="flex flex-col items-center justify-center h-full py-32 text-slate-500 space-y-6">
                      <div className="bg-white shadow-sm p-6 rounded-full animate-pulse">
                        <FileText className="w-12 h-12 text-slate-300" />
                      </div>
                      <p className="text-lg font-medium">Transcript is processing...</p>
                    </div>
                  )}
                </div>
              </ScrollArea>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
